debug: false
spring:
  profiles:
    active: dev
dubbo:
  application:
    name: rental-uc-provider
    qos-enable: false
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_null
aliyun:
  sms:
    access-key-id: LTAI4FrmjogXnDG5QiSWKCzy
    access-key-secret: J1Su96hiWgZTqIgid8xyRPG2MNOG3h
    template-code: SMS_180956831
    sign-name: 租个房